#+OPTIONS: toc:nil
#+TITLE: The Crime of Poverty by Henry George
#+TAGS: @economics
* Notes
#+BEGIN_REVIEW
Rating: ⭐⭐⭐⭐

The ideas here are from late 1800, and I'm shocked how many of the problems described here around poverty are still the same today. George's point is that poverty is a social crime, something that society ends imposing over people.

He argues that private appropriation of land leads to poverty  - where the owner is the master and others the servants.

He proposes a solution for this and is to share the revenue of land
through taxes while reducing taxes on capital and labor.

I like this idea; however, I think we are far from seeing something like this, mainly when big landowners are the ones sponsoring the people creating the laws.

The ideas mentioned here have been on the back of my mind lately, making me question things like how I invest my money. Land
speculation still offers attractive results, but I don't think they
immediately help towards progress or lifting others out of poverty. I won't stop investing in real estate. Still, George's ideas can help as another data point to evaluate the kind of projects I want to invest in. Buying a plot of land and keeping it there until the price goes up is very different from investing in a building or construction.
#+END_REVIEW

** Ideas
- Poverty is a crime imposed by society .
- Poverty comes from man's injustice to their fellows.
- When someone owns the lands, they have the power to live without work and those who do the work get less of the product of their work.
- You can't get rid of poverty as long as the element of which and from which people live is privatized.
- If you decide to be poor, that's not a crime. But if you have family and have dependents, deciding to be poor is a crime since you are imposing it into other people.
- Rarely people is poor by their own choice, it is mostly  imposed by society - and that's why poverty is a crime, a social crime, not an individual crime.
- It's society fault when a man has to decided between doing what's right and and the necessity of making a living.
- It's a contradiction to have overproduction and at the same time people starving or homeless.
- We spend more time working that on ourselves.
- Technology gets better and better and yet the struggle for existence becomes more and more intense.
- Being rich is not having more than the others but  being able to satisfy all physical wants.
- The private appropriation of natural elements from which all of us must live is a common factor of poverty across nations.
- Poverty in England started to appear with the privatization of the commons.
- He who holds the land on which and from which another man must live, is that man's master; and the man is his slave.
- Paying for a service of product is very different that paying for land, the later wasn't created and if it has a value now it is because of the community around it.
- To get rid of land monopoly or at least secure the elements necessary for life for every, instead of trying to divide the land with many people, we can divide the income that comes from the land.
- To achieve equality and securing the right to all to the elements which are necessary for life, instead of of dividing the land, we can divide the income that comes from the land through taxes. To do this, we can reduce or abolish the taxes that now rest upon capital, labor and improvements, and raising public revenue by taxation of land values.
- There is something worse than physical deprivation, something worse than starvation, that is the degradation of the mind, the death of the soul - that is what we find in big cities.
- Property can have right of property on the things they produce, but how can we have right of property on earth? which was given to us.
- It's very easy to be poor when you have no right on anything that nature give us, when you have to pay to a landowner to make a living.
