#+TITLE: Influence by Robert Cialdini
#+TAGS: @psychology @munger @decision_making

* Notes
#+BEGIN_REVIEW
Rating: ⭐⭐⭐⭐⭐

There are psychological principles and stereotypes that we have
learned to accept and made part of our decision making toolbox. Each
day we automatically rely on them to determine what is the best way to
behave under certain circumstances and help us save time and thinking
cycles.

While this is not a bug but a feature, it gives those ones who are
familiar with such principles and stereotypes a weapon which is
waiting to be exploited. The book talks about those weapons (/weapons
of influence/) and give us a framework on how to avoid them.

It shows how /reciprocation/, /commitment and consistency/, /social
proof/, /authority/, /liking/ and /scarcity/ are powerful weapons of
influence. It includes real life experiments for each weapon and the
result they had on the people they applied them.

While reading the book I couldn't stop thinking about:

 1. All the times where I have fallen victim to such weapons.
 2. /System 1/ from /Thinking Fast and Slow/.
 3. /The Elephant and The Rider/ from /The Righteous Mind/.

The people who know about such weapons, are well familiar with how
/System 1/ works or that we can barely control /The Elephant/.

5 starts! I'll recommend this book and keep going back to its ideas
from time to time.
#+END_REVIEW
** Chapter 1: Weapons of influence
#+BEGIN_VERSE
Civilization advances by extending the number of important operations
which we can perform without thinking of them.

   --Alfred North Whitehead
#+END_VERSE

Humans like some animals have a pre-programmed tape which make us act
in a certain way when there is a trigger. We can be tricked by someone
using those triggers to activate certain behaviors even when the
situation doesn't call for it.

There are many situations where we don't react in a mechanical
tape-activated way, but it is astonishing how often it does.

Automatic stereotyped behavior is prevalent in human action, because
in in many cases it is the most efficient form of behaving. Doing this
allow us to operate without having to think about each decision we are
about to make.

Some organisms copy the trigger features of other organisms in an
attempt to trick them into mistakenly playing the right behavior tape
at the wrong time. Those organisms are called /mimics/.

Humans also have exploiters who mimic trigger features to make us act
automatically. Those triggers can direct human action.

Our automatic tape developed from psychological principles or
stereotypes that we learned to accept. These principiles Cialdini says, are
weapons of influence.

#+BEGIN_VERSE
In the eye of others, each such principle is a detectable and ready weapon, a weapon of influence.

Weapons of automatic influence exist naturally around us, the exploiters can use the power of those weapons,
manipulating us without the appearance of manipulation.
#+END_VERSE

** Chapter 2: Reciprocation

#+BEGIN_VERSE
Try to repay, in kind, what other person has provided us.
#+END_VERSE

The rule of reciprocation is on the most potent weapons of influence
around us. It often produces "yes" responses to a request that, except
for an existing feeling of indebtedness, would have surely been
refused.

Uninvited favors enforce reciprocation by triggering a feeling of
indebtedness.

There are social pressures surrounding gift-giving, which leave us
with an obligation to give, an obligation to receive, and an
obligation to repay. Making it hard to turn down favoring
reciprocation arrangements.

This rule triggers unfair exchanges since small favors often stimulate
larger returns in favors.

Organizations use this weapon of influence; they send us unwanted
gifts producing a feeling of obligation, which they exploit when they
want something from us.

_Reciprocal concession:__ There is an obligation to concede to someone who has conceded to us.

** Chapter 3: Commitment and Consistency
We want to be and appear consistent with what we have already done.

Once we have made a decision, we find personal and interpersonal
pressures to behave consistently with that commitment, causing us to
respond in ways that justify our earlier decision (see [[file:bias.org::*%20Confirmation%20bias][confirmation
bias]]).

The drive to be and look consistent constitutes a potent weapon of
social influence, often causing us to act in ways that are contrary to
our own best interests.

Consistency is powerful because it is valued and
adaptive. Inconsistency is commonly thought to be undesirable. It is
in our best interest to be consistent, falling into the habit of being
automatically so.

Exploiters of this weapon structure their interactions with us so that
our own needs to be consistent will lead directly to their
benefit. They often look for commitment, that's the key. If someone
can get us to make a commitment (that is, to take a stand, to go on
the record), they will have the stage for our automatic and
ill-considered consistency with that earlier commitment.

Small commitments alter not only our future behavior but also our
self-image. Once our self-image is altered, all sorts of subtle
advantages become available to someone who wants to exploit that new
image.

The more effort that goes into a commitment, the higher its ability to
influence the attitude of the person.

We accept inner responsibility for a behavior when we think we have
chosen to perform it in the absence of outside pressure.

A question to ask yourself and avoid falling into a
commitment-consistency trap:

#+BEGIN_VERSE
If I could go back in time, will I make the same choice again?
#+END_VERSE

** Chapter 4: Social proof
#+BEGIN_VERSE
Where all think alike, no one thinks very much.

   --Walter Lippmann
#+END_VERSE

The principle of social proof is when the mean we use to determine
what is correct is to find out what other people think is right.

By looking at what other people are doing, we can have an idea of
what's the right thing to do, and it might be the right thing to do.
It gives us a shortcut on how to behave; however, it leaves us
vulnerable us to those who know how to exploit this weapon.

We are more likely to be victims of the principle of social influence
when lots of people are doing a specific action. This principle states
that the higher the number of people who find any idea correct, the
more the idea will be correct (see [[file:bias.org::Self-fulfilling%20prophecy][self-fulfilling prophecy]]).

We are vulnerable to the social proof principle when we are unsure of
ourselves, when the situation is unclear or ambiguous, when
uncertainty reigns, this is when are are most likely to look to and
accept the actions of others as correct.

Social proof can lead to __pluralistic ignore:__ in which each person
decides that since nobody is concerned, nothing is wrong. Meanwhile,
the danger may be mounting to the point where a single individual,
uninfluenced by the seeming calm of others, would react.

If you ever have a medical emergency in a public place, don't wait for
someone to help you. Choose someone from the crowd and call that
person out for help ("You in the blue jacket, call an ambulance!").

Reduce the uncertainties of those around you concerning your condition
and their responsibilities.

Social proofs operate better on us when we are looking at the behavior
of those who look like us. We are more inclined to follow the lead of
a similar individual than a dissimilar one.

The most influential leaders are those who know how to arrange group
conditions to allow the principle of social proof to work maximally in
their favor.

** Chapter 5: Liking

We prefer to say yes to the request of someone we known and like. This
rule is used by a total stranger to get us to comply with their
request.

What makes us like others?

- Physical attractiveness: This falls into a [[file:bias.org::Halo effect][halo effect]], which is when one positive characteristic of one person dominates the way that a person is viewed by others. Physical attractiveness is often such a characteristic.
- Similarity: We like people who are similar to us.
- Compliments: The information that someone fancies us can be an
  effective device for producing return liking and willing compliance.
- Contact and cooperation: We are more favorable towards the things we have contact with. Cooperating with others towards the same goals makes us like those people we are working with.
- Conditioning and association: People have an automated response to things they perceive as merely connected. For example, we dislike people who bring bad news.

To know if the effects of liking are influencing you, look at the
final result, see if you like the practitioner more than you should
under normal circumstances.

** Chapter 6: Authority
Information from a recognized authority can provide us valuable
shortcuts for deciding how to act in a situation — taking us to comply
with the wishes of properly constituted authorities, even when it
makes no sense at all.

We are vulnerable to the symbols of authority as to the
substance. Compliance professionals are experts on using those symbols
in the absence of substance.

Symbols of authority can be titles, clothes, and trappings.

A form of defense against this weapon is to be aware of authority
power. Coupling with recognition of how easily authority can be faked
will help us not to fall victim to situations where there is a
compliance attempt via the authority-influence model.

Ask yourself:

- Is this authority truly an expert?
- How truthful can we expect the expert to be here?
** Chapter 7: Scarcity
#+BEGIN_VERSE
The way to love anything is to realize that it might be lost.

   -- G.K. Chesterton
#+END_VERSE
Opportunities seem more valuable to us when their availability is limited.

The idea of potential loss plays a large role in human decision
making. It seems to be more motivated by the thought of losing
something than by the thought of gaining something of equal value (see
[[file:bias.org::Loss%20aversion%20bias][loss aversion bias]]).

When someone tells us there is a limited number of things (for example,
units of a widget), the vendor is likely using the
principle of scarcity to get us to buy something.

People find themselves doing what they wouldn't normally do, only
because the time to do so is shrinking.

The power of scarcity comes from two sources:

1. Our weakness for shortcuts. The things that are difficult to possess are typically better than those that are easy to possess. We use an item availability to decide on its quality.

2. As opportunities become less available, we lose freedom; we hate to lose the freedom we already have. This desire to preserve our established prerogatives is the centerpiece of psychological reactance theory.

Reactance theory: when free choice is limited or threatened the need
to retain our freedoms makes us desire them (as well as the goods and
services associated with them) significantly more than previously.

When increasing scarcity-or-anything else interferes with our prior
access to some item, we will react against the interference by wanting
and trying to possess the item more than before.

We rarely recognize that psychological reactance has caused us to want an item more.

The scarcity principle not only applies to commodities but also other things like information. It doesn't have to be restricted for us to value it more, it just needs to be scarce.

When not only want something when it is scarce, we want it more when
we compete for it.

The joy is not in experiencing a scarce commodity but in possessing
it. Whenever we confront the scarcity pressures surrounding an item, we must also confront the question of what it is we want from it.

We barely want a thing for the sake of owning it, we want it because
of its utility value. Scarce resources do not taste or feel or sound or ride or work any better because of their limited availability.
